name: Deploy to Development
on:
  push:
    branches: [release/production]
jobs:
  Build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18.x]
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: mkdir ~/.ssh
      - run: echo "$SSH_KEY" >> ~/.ssh/github-action
      - run: chmod 600 ~/.ssh/github-action
      - run: echo -e "Host vps\n\tUser kajur-app\n\tHostname 103.127.96.31\n\tPubKeyAuthentication yes\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
      - name: "[RUNNER] Copy new file"
        run: rsync -ae ssh ./ vps:/home/kajur-app/hf-emotion-detection-api/
      - name: "[RUNNER] Go to directory"
        run: ssh vps "cd /home/kajur-app/hf-emotion-detection-api/"
      - name: "[RUNNER] Install dependencies"
        run: ssh vps "npm install --omit=dev"
      - name: "[SERVER] Restart app"
        run: ssh vps "source ~/.nvm/nvm.sh && pm2 restart ${{ secrets.APP_NAME }}"